### ISSUE TITLE
[Bug] Button Custom Card refreshes every few seconds

### ISSUE THREAD

**Issue by rkkhanna** [ngocjohn/vehicle-status-card#11]
### Short summary 📝

Pop-up button custom card refreshes intermittently every few seconds in a loop

### Detailed description 📋

Using one of the buttons to show a custom card, the card pop-up refreshes intermittently in a loop. In another [thread](https://github.com/ngocjohn/vehicle-info-card/issues/52#issuecomment-2362918263), @ngocjohn identified it as '_card tearing problem_'. Facing the same with this card as well. Screen record below shows the issue:

https://github.com/user-attachments/assets/3c6c50b5-057b-4c19-986e-4be47c398f58

### Version 📌

1.1.0

### Environment 🌐

Vivaldi, Edge, Windows 11

**Comment by ngocjohn** [comment]
Hi @rkkhanna , please test the beta [v1.1.1-beta_2](https://github.com/ngocjohn/vehicle-status-card/releases/tag/v1.1.1-beta_2) .. If everything is fine, I will release it as an offic release. 😉 The same bug will be fixed in info-card 😄

**Comment by rkkhanna** [comment]
> Hi @rkkhanna , please test the beta [v1.1.1-beta_2](https://github.com/ngocjohn/vehicle-status-card/releases/tag/v1.1.1-beta_2) .. If everything is fine, I will release it as an offic release. 😉 The same bug will be fixed in info-card 😄

Hi @ngocjohn, just applied the beta version. It works perfect! Issue is resolved in the beta version.
Looking forward to the fix in `vehicle-info-card` too.

Thank you!
