### ISSUE TITLE
[Feature] Drop and drop to reorganize button list order

### ISSUE THREAD

**Issue by rkkhanna** [ngocjohn/vehicle-status-card#16]
### Short summary

Add ability to drag and drop button to new location in button list configuration

### Detailed description

Currently, there is no feature to reorder buttons in button list configuration. The only way to reorder the buttons is to delete and define them again. It would be nice to have handles to drag and drop, like the handles provided in Single Indicators configuration to reorder the indicators.

![image](https://github.com/user-attachments/assets/d569c272-3885-498d-812a-aa76a1535b8a)

### Examples 🖼️

Screenshot of Single Indicators configuration that has handles to drag and drop indicators in their desired position.

### Additional context 🗒️

![image](https://github.com/user-attachments/assets/f8ecb2a1-9a60-4b34-881f-2a35cdf96399)

_No response_

**Comment by ngocjohn** [comment]
@rkkhanna  Feat added.. 🎉 
![2024-10-03 19 10 38](https://github.com/user-attachments/assets/920e9c6a-0f82-4e48-98c0-8d8206623956)
