### ISSUE TITLE
[Bug] Tap interactions no longer working after 2024.10 update

### ISSUE THREAD

**Issue by Tomanic-glitch** [ngocjohn/vehicle-status-card#18]
### Short summary 📝

Tap interactions for Button type Action no longer working after 2024.10 update

### Detailed description 📋

After updating yesterday to Home Assistant 2024.10 it seems that the Tap interactions for Button type Action are no longer working, nothing happens after performing either Tap/Hold/Double tap action.

### Version 📌

v1.1.1

### Environment 🌐

Chrome on Windows 11, Android 15

**Comment by ngocjohn** [comment]
Hi @Tomanic-glitch , So I have tested card with new version of HA, for me the button action works without problems. Can you describe your problem in more detail, or preferably add the yaml config?

**Comment by Tomanic-glitch** [comment]
Hi @ngocjohn, I'm attaching the yaml and screenshot of the card. Each of the 6 configured buttons (Doors, Trunk, Ventilation...) do have Tap actions configured but nothing happens when tapping them. I only noticed the issue after yesterdays update to 2024.10, everything worked before.

![vehicle_card](https://github.com/user-attachments/assets/a8c68404-f85d-4774-b9ea-1681b24c6caa)
[vehicle_card.txt](https://github.com/user-attachments/files/17241753/vehicle_card.txt)

**Comment by ngocjohn** [comment]
@Tomanic-glitch Zkus stahnout znovu posledni verzi a smazat v prohlizeci cache. Mne funguje veskera akce, jak v telefonu, tak normalne v prohlizeci  🤷

**Comment by Tomanic-glitch** [comment]
@ngocjohn Zkusil jsem a pořád stejný. Ale asi to bude problém přímo s mojí kartou, když jsem zkusil udělat test s úplně novou tak akce fungují normálně 🤷 Každopádně moc díky za tuhle kartu, skvělá práce!
