### ISSUE TITLE
[Bug] Using token from secrets.yaml in Custom Button yaml gives error

### ISSUE THREAD

**Issue by rkkhanna** [ngocjohn/vehicle-status-card#27]
### Short summary 📝

Using token from secrets.yaml in yaml code for custom button card gives error

### Detailed description 📋

Cannot use a token from `secrets.yaml` in yaml code for a custom button card. Doing so gives an error. Refer screenshot below.

![image](https://github.com/user-attachments/assets/bf9eee36-1a75-4938-8729-3f6a7a1b57ab)

If I remove secret token and replace with embedded value of the token, the error goes away.

Thanks!

### Version 📌

v1.3.0

**Comment by ngocjohn** [comment]
Hi @rkkhanna,  if you are using the GUI editor as storage mode. You can't use secret, it only works in pure yaml mode. 😄

**Comment by rkkhanna** [comment]
> Hi @rkkhanna, if you are using the GUI editor as storage mode. You can't use secret, it only works in pure yaml mode. 😄

Hi @ngocjohn, I use GUI editor to configure card and then copy entire yaml code for the card and paste it in `lovelace.yaml`. I use lovelace in yaml mode, not using dashboards. Will it not work in this situation?

Thanks!

**Comment by ngocjohn** [comment]
@rkkhanna Yes, if you paste it into lovelace.yaml, it will work.

**Comment by rkkhanna** [comment]
> @rkkhanna Yes, if you paste it into lovelace.yaml, it will work.

Ok, let me check it out. Will revert.

Thanks!

**Comment by rkkhanna** [comment]
> > @rkkhanna Yes, if you paste it into lovelace.yaml, it will work.
> 
> Ok, let me check it out. Will revert.
> 
> Thanks!

Hi @ngocjohn, it did work. Thank you for your prompt response and for clarifying this. Much appreciated.

As an aside, I love the power of `vehicle-status-card`, especially options for Single and Group indicators. Originally used it for Tesla, but then also migrated MB EQS card to this from your original `vehicle-info-card` 😊

Thank you creating these excellent cards! Closing this bug report.

**Comment by ngocjohn** [comment]
Thanks, yes, the status card is more about invidual customization. With the mercedes card the data is automatically generated.. 😄
