### ISSUE TITLE
[Bug] Map wont show location

### ISSUE THREAD

**Issue by blair287** [ngocjohn/vehicle-status-card#28]
### Short summary 📝

The mini map doesnt show location just expanding circles

### Detailed description 📋

The mini map wont show the location just has the expanding circles the device tracker entity is working fine i can see location on home assistants maps.

### Version 📌

1.3

### Environment 🌐

All

### Logs and screenshots 📂

![vehicle card issue](https://github.com/user-attachments/assets/aaf47d6c-aa16-4179-ae77-da25be3070ec)

**Comment by ngocjohn** [comment]
Hi, I've updated the methods for getting the address from the map location and modified the mini map popup, I'll release the fix in the next release. 👍
