### ISSUE TITLE
[Feature] Tyre pressure page

### ISSUE THREAD

**Issue by horfic** [ngocjohn/vehicle-status-card#3]
### Short summary

Backport tyre pressure page from vehicle-info-card

### Detailed description

Hi,
i really like this card and was wondering if the tyre pressure card could be backported to vehicle status card.

So basically to provide an image for the middle and select for each corner the tyre pressure entity

cheers,
horfic

**Comment by ngocjohn** [comment]
Yes, I have some changes ready for release. I will add this feat request to the list of changes as well .. 
![custom-tire-bg](https://github.com/user-attachments/assets/4ca4088b-8a47-44a3-9782-c0a4769f70a7)

**Comment by horfic** [comment]
Thats awesome

![share_3698285314071234203](https://github.com/user-attachments/assets/30d9ec20-73dc-4faf-bfaf-e2f77ac9e67e)
As bmw api does not allow to get a birdsview image, they are using the rear image for tire page at the oem app

Just to provide you extended view on image availability

**Comment by horfic** [comment]
here the image itself for testing purposes
![rear](https://github.com/user-attachments/assets/7ee4f426-1143-4380-81a9-311fe891a1d4)

**Comment by ngocjohn** [comment]
sneak peek 🤫 
![custom-tire](https://github.com/user-attachments/assets/082dc472-b684-4525-8a17-94c587512234)
