### ISSUE TITLE
[Bug] Notify template

### ISSUE THREAD

**Issue by tomdevos2401** [ngocjohn/vehicle-status-card#30]
### Short summary 📝

the notification template does not work

### Detailed description 📋

I have a simple template **_{{ is_state('binary_sensor.x5_xdrive50e_door_lock_state','on') }}_** which gives true or false. when it turns to true, there is no badge icon displayed.

### Version 📌

v1.3.1

**Comment by ngocjohn** [comment]
Hi @tomdevos2401 , have you tried setting it to true instead of on? 
```yaml
 {{ is_state('binary_sensor.x5_xdrive50e_door_lock_state', true) }}
```

**Comment by tomdevos2401** [comment]
hi @ngocjohn , i did. 

What's odd is that the notify template is not saved when I press the save button. no matter what I enter. 
so i fixed it by adding it immediately in the code editor.

**Comment by ngocjohn** [comment]
Right now I'm changing the whole way to get the template value. Fix will be in the new release as soon as possible. 👍
