### ISSUE TITLE
[Bug] Indicators not shown when logged in user is not administrator

### ISSUE THREAD

**Issue by mtjoernelund** [ngocjohn/vehicle-status-card#31]
### Short summary 📝

Dashboard where the logged in HA user is a local user without admin privileges does not show indicators - single nor group

### Detailed description 📋

When the user signed in is a local user with no admin privileges in HomeAssistant, configured indicators (whether single or groups) does not show. The same view shown when an admin account is logged into HomeAssistant renders as expected. 

### Version 📌

v1.3.1

### Environment 🌐

Both Chrome on Android and Safari on MacOS

### Logs and screenshots 📂

Screenshot from page with admin-user logged in:
<img width="280" alt="Skærmbillede 2024-11-22 kl  17 00 56" src="https://github.com/user-attachments/assets/6c1da12a-0a23-4c24-acae-e47a99b315c0">

Picture of the same page with non-admin user logged in:
<img width="345" alt="Skærmbillede 2024-11-22 kl  17 01 35" src="https://github.com/user-attachments/assets/8add995a-ca3a-436c-a415-f510694c5f4a">

**Comment by ngocjohn** [comment]
Hi @mtjoernelund, I'll take a look at it this weekend and see what the problem is.
