### ISSUE TITLE
[Bug] Doesn't work on my wife's phone.

### ISSUE THREAD

**Issue by Ferrox85** [ngocjohn/vehicle-status-card#33]
### Short summary 📝

The status card is not completely loaded on an other device

### Detailed description 📋

At my wife's home assistant account the card is not loaded properly. On my account it works fine.

This card shows up with only battery and fuel states, picture and map under my wife's account. The other like indicators and button and card doesn't show up.  Se pictures in the logs and screenshots

### Version 📌

V1.3.1

### Environment 🌐

Safari on iPhone and Chrome (ARC) on macbook

### Logs and screenshots 📂

This warning we both get:

Warning:
`vehicle-status-card.js?hacstag=859371663131:72 Swiper Loop Warning: The number of slides is not enough for loop mode, it will be disabled and not function properly. You need to add more slides (or make duplicates) or lower the values of slidesPerView and slidesPerGroup parameters`

JS where this thrown:
`function le(t) {
    try {
        return void console.warn(t)
    } catch (t) {}
}`

Console logs gives the following errors if I am logged in as my wife, i don't get these:

3 times these errors:
Post error on api/template:
`fetch-with-auth.ts:20 
POST http://homeassistant.thuis:8123/api/template 401 (Unauthorized)`

`vehicle-status-card.js?hacstag=859371663131:2624 Uncaught (in promise) Error: Error evaluating template: [object Object]
    at bn (vehicle-status-card.js?hacstag=859371663131:2624:1989)
    at async yn (vehicle-status-card.js?hacstag=859371663131:2624:2239)
    at async so._getSingleIndicators (vehicle-status-card.js?hacstag=859371663131:2877:6452)
    at async Promise.all (index 0)
    at async so._handleFirstUpdate (vehicle-status-card.js?hacstag=859371663131:2877:6349)`

The JS where the error is thrown:
`async function bn(t, e) {
    if (!t || !e)
        return "";
    try {
        return await t.callApi("POST", "template", {
            template: e
        })
    } catch (t) {
        throw new Error(`Error evaluating template: ${t}`)
    }
}`

My view:
<img width="404" alt="Scherm­afbeelding 2024-11-23 om 20 46 08" src="https://github.com/user-attachments/assets/b906b40f-e818-4173-9dbc-cf158412d41c">
My Wifi's view (same card):
<img width="412" alt="Scherm­afbeelding 2024-11-23 om 20 46 18" src="https://github.com/user-attachments/assets/02bfba86-8de1-420f-bbdb-df41e4cbe99f">

**Comment by Ferrox85** [comment]
I also get the invalid authentication error like in the mentioned issue. But I've tracked it down to this card. Maybe it is related somehow.

**Comment by ngocjohn** [comment]
Hi @Ferrox85, the [fix ](https://github.com/ngocjohn/vehicle-status-card/pull/32)is ready. The new version will be ready after the weekend. 😄

**Comment by Ferrox85** [comment]
Damn, missed that. That is quick!
Hopefully it fixes the invalid login errors to.

**Comment by ngocjohn** [comment]
Yes, login error is associated with it, so fixed.

**Comment by ngocjohn** [comment]
Btw, what kind of car is that? It looks cool

**Comment by Ferrox85** [comment]
Haha, thats a Lynk & Co 01 plugin hybrid. Very populair in holland right now. And a fine car. It is based on a volvo xc40.

**Comment by ngocjohn** [comment]
Hi @Ferrox85, I added this fix in the last release. Can you please confirm if this problem is solved? 😄

**Comment by Ferrox85** [comment]
Yes it did, but it Mixed up the fonts?

![image](https://github.com/user-attachments/assets/2385b195-a0a8-48e4-93ef-122f35eb58ac)

When I edit the dashboard it is working correct again. But reopening home assistant and it is back again. I am not sure whether it is an cache issue. Restarting home assistant does not help either.

**Comment by ngocjohn** [comment]
@Ferrox85 That's strange, I didn't modify any css changes. Can you copy here the config for the button where the problem occurs?  
![2024-11-27 19 51 48](https://github.com/user-attachments/assets/a4872058-7c61-4e18-aba0-3a6c4efc8cea)

**Comment by ngocjohn** [comment]
btw any problem with the frontend, that means dashboard lovelace is not solved by restarting HA, but by clearing the cache in the browser. Or reset the frontend cache in the mobile app. 

# How to Clear Cache for a Specific Page in Popular Browsers

---

## Safari
1. Open Safari and navigate to the specific page you want to clear the cache for.
2. Click on **Safari** in the top menu bar and select **Preferences** (or press `Command + ,`).
3. Go to the **Privacy** tab and click **Manage Website Data**.
4. Use the search bar to find the specific site or page.
5. Select the site from the list and click **Remove**.
6. Confirm by clicking **Done**.

---

## Google Chrome
1. Open Chrome and go to the page you want to clear the cache for.
2. Click the three-dot menu in the top-right corner and select **More Tools** > **Developer Tools** (or press `Ctrl + Shift + I` / `Command + Option + I`).
3. In the Developer Tools panel, right-click on the refresh button (🔄) in the toolbar.
4. Choose **Empty Cache and Hard Reload**.

---

## Mozilla Firefox
1. Open Firefox and navigate to the page you want to clear the cache for.
2. Click the three-line menu (hamburger icon) in the top-right corner and select **Settings** (or **Options**).
3. Go to the **Privacy & Security** section.
4. Scroll down to **Cookies and Site Data** and click **Manage Data**.
5. Search for the specific site in the search bar.
6. Select the site and click **Remove Selected**.
7. Confirm by clicking **Save Changes**, then **Remove**.

---

for companion app 
In the iOS app. 
```
Sidebar > setting > companion app  > debugging> reset frontend cache
```
there will be something similar for android

**Comment by Ferrox85** [comment]
On my mac this problem isn't there. In incognito it goes correct to, so It is weird that flushing the cache on the compagnion app doesn't work properly apperently.
