### ISSUE TITLE
[Feature] Tire pressure state color

### ISSUE THREAD

**Issue by thib5** [ngocjohn/vehicle-status-card#36]
### Short summary

Add Color to tire pressur 

### Detailed description

Hi,
I have a sensor for my car that provides a color (green for OK, yellow for warning, and red for critical). The sensor is sensor.2025_chevrolet_equinox_ev_tire_pressure_right_rear_message (state = GREEN).
Would it be possible to use this sensor to set the font color of the tire pressure card (for each tire)?

**Comment by ngocjohn** [comment]
Hi @thib5, yes, it's possible. I will add additional color template options for each pressure state 👍

**Comment by ngocjohn** [comment]
@thib5 update 🎉 
I added this feature to the card, did you mean something like this? 
I'll test a few more things and I can release a beta version with this enhancement. 
![CleanShot 2024-11-27 at 18 54 22](https://github.com/user-attachments/assets/507ce9d4-f8fc-42eb-af5e-15ffc9be22a6)
