### ISSUE TITLE
[Bug] Button-Fontsize in HA mobile interface

### ISSUE THREAD

**Issue by gethash** [ngocjohn/vehicle-status-card#42]
### Short summary 📝

The font-size of buttons is not consistent in the home assistant mobile app for iOS

### Detailed description 📋

As you can see, the font-size for buttons are not consistent using the iOS mobile app. I cannot reproduce this using developer tools in Safari or chrome to have this on the desktop or pure safari (it works there). I am also not able to find a spot to configure this correctly. As a workaround I can probably force this using some css and media queries but perhaps there is a better or know way to solve this (non critical) issue. Thanks for the good work!

### Version 📦

v1.4.2

### Environment 🌐

Home Assistant Ios

### Logs and screenshots 📂

![IMG_E8D526635714-1](https://github.com/user-attachments/assets/58ae8405-81b8-4963-883e-97550f23c024)

**Comment by ngocjohn** [comment]
@gethash Hi, check the HA app settings, if the page zoom is not more than default (100%), then it has a problem with the font size. 
```
Setting > Companion app > General > Page zoom 
```
Or you can log into HA via the mobile browser to see if there is a problem with the app.

**Comment by gethash** [comment]
Sorry for the late reply. I have tried both and and when I change the page zoom to 85% and back to 100% (like it was before), than it works for the first load, but if a force a reload it is "broken" again. Use card_mord works in the browser but seems to be ignored in the companion app. I'll wait for the text release and give you feedback. Thanks so far!

**Comment by ngocjohn** [comment]
Hi @gethash there is new version 1.4.3, try it. 😄

**Comment by gethash** [comment]
Thanks for coming. Tried it and still have the some issue. I try to investigate further what's responsible for this in the mobile app
