### ISSUE TITLE
Indicator bar

### ISSUE THREAD

**Issue by jackshaw20** [ngocjohn/vehicle-status-card#43]
### Short summary 📝

service dropdown actions

### Detailed description 📋

on the indicators at the top, on your demo it shows clicking a group 'services' opening a drop down with action buttons but can't find an option to configure this.   I don't have a Mercedes therefore can't use your other card. 

### Version 📦

v1.4.2

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/1872e46d-aef0-40b8-871a-e34511f9cd11)

**Comment by ngocjohn** [comment]
Hi @jackshaw20, unfortunately this function is only available in the card for Mercedes.
