### ISSUE TITLE
[Bug] Range Progress Bar Not Accurate

### ISSUE THREAD

**Issue by giuseppebaldi** [ngocjohn/vehicle-status-card#46]
### Short summary 📝

Progress bar for fuel doesn't display accurately.

### Detailed description 📋

I have a range progress bar setup with 2 entities; 1 showing the current fuel level (7.8 gal as of right now) and another entity showing the fuel capacity (26 gal). The progress bar generated by the card shows what looks like about 10% fuel level vs capacity when 7.8 gal of 26 gal capacity should show a bar of about 30% or roughly a third of the bar. I am on version 1.4.3.

### Version 📦

v1.4.2

### Environment 🌐

Chrome on Windows 11

### Logs and screenshots 📂

![Screenshot 2024-12-24 121529](https://github.com/user-attachments/assets/b00c0d7d-dff0-453d-81b2-5d66164b2b2e)

**Comment by ngocjohn** [comment]
Hi @giuseppebaldi , the progress bar is made up of 2 entities one for fuel level and a second entity for range level. Example fuel 7.8gal, 20 miles range

**Comment by giuseppebaldi** [comment]
Oh, I see. I guess I misunderstood. So it's one entity for current fuel level and one for current range or total range when full? I guess I'm still confused as to what exactly the progress bar is supposed to represent, I thought it was to show percentage of fuel OR range remaining. Below is a screenshot using current fuel level and current range, which doesn't generate a bat that makes sense to me because 13 gallons is about half a tank and my total range when do it's about 400 miles.
![Screenshot_20241225-094040](https://github.com/user-attachments/assets/9f504574-1a96-4c2a-a9ee-d81a349cf5d9)

**Comment by ngocjohn** [comment]
Yes, the main indicator is the fyuel/battery level ...which determines the percentatage. and sets the percent progress bar, the other just shows the range progress how much range is left.

**Comment by giuseppebaldi** [comment]
So how does the percentage get set if it doesn't know the capacity of fuel the vehicle is capable of holding? For instance, in the above vehicle 13 gallons is approximately half a tank but the progress bar shows there's only about 1/8th of a tank left, indicating that the vehicle can hold ~ 105 gallons. It just doesn't seem to give an accurate visual representation of remaining fuel or range. 

Am I missing something or misunderstanding?

**Comment by ngocjohn** [comment]
Hi, for the energy level the entity must have a state in %. The bar will be colored as a state of 100%.

**Comment by giuseppebaldi** [comment]
Got it, thank you.
